## Add this file to your meteor package as `.circle.yml`

machine:
  node:
    version: 0.10.33
  pre:
    - curl -L https://git.io/vKvNt | /bin/sh
test:
  override:
    - node /home/ubuntu/start_test.js
